# config.yml
# ===============================================
# Settings for the Real-time Job Consumer/Watcher
# ===============================================
job_consumer_settings:
  job_directory: "D:\\subplz-jobs"
  subplz_command: "subplz"
  subplz_args:
    - "helpers/subplz.sh"
    - "{directory}"
  path_map:
    "/media/": "D:\\Media\\"
    "/data/ja-anime/": "D:\\Media\\J-Anime Shows\\"
  error_directory: "D:\\subplz-jobs\\failed"

# ==========================================================
# Settings for the Scheduled Library Scanner ("Gap-Filler")
# ==========================================================
scanner_settings:
  content_dirs:
    - "D:\\Media\\J-Anime Shows\\"
    - "D:\\Media\\J-Shows\\"
  target_sub_extension: ".ja.srt"
  blacklist_filenames: ["OP", "ED", "NCOP"]
  blacklist_dirs: ["新しいフォルダー", "New folder", "Specials"]